/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package persistence;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Careen Emilza
 */
public class RegistFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistFrame
     */
    public RegistFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblREG = new javax.swing.JLabel();
        lblUSN = new javax.swing.JLabel();
        lblPWD = new javax.swing.JLabel();
        txtUSN = new javax.swing.JTextField();
        pwfPWD = new javax.swing.JPasswordField();
        btnREG = new javax.swing.JButton();
        lblTNY = new javax.swing.JLabel();
        lblLOG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblREG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblREG.setText("REGISTRASI");

        lblUSN.setText("Username");

        lblPWD.setText("Password");

        btnREG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnREG.setText("REGIST");
        btnREG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGActionPerformed(evt);
            }
        });

        lblTNY.setText("Sudah Mempunyai Akun?");

        lblLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLOG.setText("LOGIN");
        lblLOG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLOGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblREG))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUSN)
                            .addComponent(lblPWD))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwfPWD, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtUSN)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnREG))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblTNY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLOG)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblREG)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUSN)
                    .addComponent(txtUSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPWD)
                    .addComponent(pwfPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnREG)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTNY)
                    .addComponent(lblLOG))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnREGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGActionPerformed
        if (txtUSN.getText().isEmpty() || String.valueOf(pwfPWD.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi username dan password terlebih dahulu.");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersistencePU");
            EntityManager em = emf.createEntityManager();

            try {
                em.getTransaction().begin();

                // Ambil data username dan password dari input pengguna
                String username = txtUSN.getText();
                String password = String.valueOf(pwfPWD.getPassword());

                Datalogin existingUser = em.find(Datalogin.class, username);

                if (existingUser != null) {
                    JOptionPane.showMessageDialog(null, "Username sudah terdaftar. Gunakan username lain.");
                    txtUSN.requestFocus();
                } else {
                    Datalogin newUser = new Datalogin();
                    newUser.setUsername(username);
                    newUser.setPassword(password);

                    em.persist(newUser);

                    em.getTransaction().commit();

                    JOptionPane.showMessageDialog(null, "Registrasi berhasil! Silakan login menggunakan akun Anda.");

                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);
                    this.dispose(); // Tutup form registrasi
                }
            } catch (Exception ex) {
                em.getTransaction().rollback(); 
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
                ex.printStackTrace();
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_btnREGActionPerformed

    private void lblLOGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLOGMouseClicked
        LoginFrame yes = new LoginFrame();
        yes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLOGMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnREG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLOG;
    private javax.swing.JLabel lblPWD;
    private javax.swing.JLabel lblREG;
    private javax.swing.JLabel lblTNY;
    private javax.swing.JLabel lblUSN;
    private javax.swing.JPasswordField pwfPWD;
    private javax.swing.JTextField txtUSN;
    // End of variables declaration//GEN-END:variables
}
